services:
  moderator_api:
    env_file: secrets/.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moderator_container
    ports:
      - "8003:8000"
    volumes:
      - ./src:/app/src
    restart: unless-stopped
