services:
  redis:
    image: redis:7
    ports:
      - "6377:6377"
    restart: unless-stopped

  moderator_api:
    env_file: secrets/.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moderator_container
    ports:
      - "8003:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    restart: unless-stopped
